name: yelahanka_gds_training
description: A training app for Gramin Dak Sevaks on marketing skills.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.0
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.0
  file_picker: ^5.2.10
  path_provider: ^2.0.15
  pdfx: ^2.4.0
  provider: ^6.0.5
  intl: ^0.18.0
  share_plus: ^7.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
